services:
  setup:
    image: rhex-local:1.0.42-r3
    pull_policy: never

  web:
    image: rhex-local:1.0.42-r3
    pull_policy: never

  worker:
    image: rhex-local:1.0.42-r3
    pull_policy: never
